create hbr731.md
treehouses/treehouses.github.io pull request #108
Opened 2019-09-02 05:43 UTC by hbr731

https://raw.githubusercontent.com/hbr731/hbr731.github.io/setup/pages/vi/profiles/hbr731.md

2019-09-02 19:43 UTC, dogi requested changes

2019-09-02 19:43 UTC, dogi commented on pages/vi/profiles/hbr731.md
> +<code> Coffee and my computer xD </code>
please don't use html
markdown has its own syntax

2019-09-02 19:43 UTC, dogi commented on pages/vi/profiles/hbr731.md
> +<code> Java, C#, C++, Assembly(MASM), Javascript, Python, Scheme </code>
same as above

2019-09-02 19:43 UTC, dogi commented on pages/vi/profiles/hbr731.md
> +<code> React, React-Redux, Spring, Node.js, Express </code>
same as above

2019-09-02 19:43 UTC, dogi commented on pages/vi/profiles/hbr731.md
> +<code> MongoDB, SQL, PostgreSQL </code>
same as above

2019-09-02 19:45 UTC, dogi commented
also it would be nice you add a link or a linked picture

2019-09-03 03:06 UTC, lmmrssa reviewed
@hbr731 some more markdown syntax will look nice

2019-09-19 17:26 UTC, vmnet8 commented
Also please put the raw.githack.com link.

2019-10-19 00:50 UTC, closed without merging