Create rpi-vi-first-steps.md
treehouses/treehouses.github.io pull request #11
Opened 2019-08-06 09:53 UTC by ArranHL

@dogi this is the more streamlined version that will need additional supporting documents, let me know if this is still too much content to include and I'll strip down further

2019-08-07 11:42 UTC, ArranHL commented
First supporting image is Files for New10Steps #14

2019-08-07 14:32 UTC, dogi commented
found the file ... it is in the root ... we should change that ...

anyhow https://raw.githack.com/treehouses/treehouses.github.io/slimNew10Steps/#!rpi-vi-first-steps.md

2019-08-07 14:47 UTC, ArranHL commented
hi @dogi I was going to create a "vi" folder in pages(folder) but thought that you could not create an empty folder without first having a file to add to it, should of created #11 directly in pages/vi as a new file

Should I do a new PR of is there a way of changing the destination?

2019-08-07 14:56 UTC, ArranHL commented
@dogi nvm got it :)

2019-08-07 15:03 UTC, dogi commented
generally like what I see
still have not gone totally over it

2019-08-07 15:13 UTC, ArranHL commented
@dogi awesome, I've put together a very brief little flow chart that you can access here: https://drive.google.com/file/d/1ODMvX6IY_QQs_0fdRc4vSMO1dqL3hfA0/view?usp=sharing 

If you'd like to add any specific ideas.
![image](https://user-images.githubusercontent.com/47016295/62634642-eb66bb00-b93e-11e9-8a6d-6047a1c62d31.png)

I was thinking of an introductory step specifically focused on getting them more involved with Cli

2019-08-07 21:35 UTC, dogi commented
https://raw.githack.com/treehouses/treehouses.github.io/slimNew10Steps/#!pages/vi/rpi-vi-first-steps.md

2019-08-07 22:00 UTC, dogi requested changes
@ArranHL good start ;) still too much open-learning-exchange :P

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will have the opportunity to work with software and languag
and hardware https://raspberrypi.org

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +Welcome to the first steps for becoming an OLE Virtual Intern! We treat these first steps as a vetting process to prove that you can follow simple instructions before you can progress to working on h
OLE Virtual Intern => Virtual Systems Engineering Intern @ OLE project treehouses.io

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  A Raspberry Pi 4
Raspberry Pi 4b  link to https://www.raspberrypi.org/products/raspberry-pi-4-model-b/ (all rpis 3 and greater work)

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +	- minimal 16GB, but we recommend 32GB or greater
16gb (and greater) but we recommend U1 speed class

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  Ethernet cable or wifi dongle
wifi dongle? plz remove

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  USB keyboard, monitor, and HDMI cable
please move this to last place and with optional

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  8 GB of hard-drive space
remove ;)

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  8 GB of memory (RAM)
yes like this
but we should write we suggest a laptop with 8 and more gb ram

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +2. Create a [GitHub account](https://github.com/) then watch <a href="https://github.com/open-learning-exchange/open-learning-exchange.github.io" target="_blank">Open Learning Exchange's github.io re
we should add mostly active treehouses people

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +2. Create a [GitHub account](https://github.com/) then watch <a href="https://github.com/open-learning-exchange/open-learning-exchange.github.io" target="_blank">Open Learning Exchange's github.io re
treehouses github please

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +**NOTE**: See the [Planet User Manual](#!./pages/techgenius/tg-planet-user-manual.md) for an overview of functionality and an explanation of various terms. Your contributions will not only help us ou
remove

2019-08-07 22:00 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +3. We use Crowdin to translate our user interface into many different languages. If you know another language besides English, we would greatly appreciate if you would help translate. To do so, go to
remove?

2019-08-08 00:05 UTC, dogi approved these changes

2019-08-08 00:05 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +Make sure that you've linked to your github.io and pull request link on the [Gitter chat](https://gitter.im/open-learning-exchange/chat) (https://YourUserName.github.io and `LinkToYourPullRequest`).
treehouses Lobby

2019-08-08 00:05 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +Follow the tutorial under the NEW .md PROCESS NEEDED to create at least one issue. Post a link in [Gitter](https://gitter.im/open-learning-exchange/chat) whenever you create an issue or when you comm
treehouses Lobby

2019-08-08 00:05 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +The MDwiki has plenty of resources to help you complete the steps. There is a list of useful links at the end of each step. We also created a [FAQ page](https://open-learning-exchange.github.io/#!./p
no ole.gh.io

2019-08-08 00:05 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +**We also want you to keep us updated a relatively good amount in the Gitter chat as you complete these steps. We will ask you to send us messages, links, and screenshots along the First Steps, and w
no ole.gh.io

2019-08-08 01:43 UTC, dogi approved these changes
@samuelchen1213 we are close ;)

2019-08-08 01:43 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +1.  A Raspberry Pi 4 ([Pi 4 information](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/))
rpi3 s are missing

2019-08-08 01:43 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +	- Standard micro USB power cord: 15.3W for Pi 4
usb-c for rpi4b

2019-08-08 01:43 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +6.  USB keyboard, monitor, and HDMI cable
plz but under optional on the end of this list

2019-08-08 01:43 UTC, dogi commented on pages/vi/rpi-vi-first-steps.md
> +Make sure that you've linked to your github.io and pull request link on the [Gitter chat](https://gitter.im/open-learning-exchange/treehouses) (https://YourUserName.github.io and `LinkToYourPullReque
gitter Lobby

and

link needs to have .../Lobby

2019-08-08 04:03 UTC, dogi approved these changes

2019-08-08 04:03 UTC, samuelchen1213 approved these changes

2019-08-08 04:04 UTC, merged