Update dead link (Fix #96)
treehouses/treehouses.github.io pull request #113
Opened 2019-09-03 04:41 UTC by phamduchongan93

Fix the broken link:

> NOTE: You can track your progress with the number of pull requests and issues 

[raw githack link](https://raw.githack.com/phamduchongan93/phamduchongan93.github.io/fix_issue_96/#!pages/vi/github-issues.md)
This PR close #96

2019-09-03 18:30 UTC, dogi requested changes
@phamduchongan93 please use `git rm ...` to remove the additional file

2019-09-03 18:30 UTC, dogi commented on pages/vi/profiles/xdmtk.md
> +
this file is too much

2019-09-04 00:24 UTC, hiroTochigi reviewed
![image](https://user-images.githubusercontent.com/44413241/64216824-31e90000-ce80-11e9-8839-dcd210e401a7.png)
It does not render photo correctly.

2019-09-04 01:56 UTC, lmmrssa commented
@phamduchongan93 you should keep master branch synchronized and always create branch from master not from previous branch

2019-09-04 19:21 UTC, phamduchongan93 commented
Yeah, I understood the issue, but I'm struggling to keep the integrity of my master branch. There is some error during the forking process that I'm trying to figure out.

2019-09-04 22:53 UTC, dogi approved these changes

2019-09-04 22:54 UTC, lillyxxx approved these changes

2019-09-04 22:55 UTC, merged