Add CalebProvost to team.md
treehouses/treehouses.github.io pull request #124
Opened 2019-09-05 00:41 UTC by CalebProvost

I've met the requirements of Step 8 and followed Step 9.
I'm looking forward to scheduling a meeting for joining the team.

2019-09-05 01:18 UTC, dogi requested changes
on hold

2019-09-06 08:23 UTC, lmmrssa approved these changes

2019-09-06 23:47 UTC, lillyxxx approved these changes

2019-09-06 23:48 UTC, hiroTochigi approved these changes

2019-09-06 23:53 UTC, dogi reviewed
@CalebProvost congr

2019-09-06 23:53 UTC, CalebProvost commented
https://raw.githack.com/CalebProvost-OLE/CalebProvost-OLE.github.io/AddTeamMember/#!pages/vi/team.md

2019-09-06 23:54 UTC, dogi approved these changes

2019-09-06 23:54 UTC, dogi commented on pages/vi/team.md
> +|[CalebProvost](profiles/CalebProvost.md)|2019-09-04|
congrats @CalebProvost ;)

2019-09-07 00:04 UTC, merged