Update team.md
treehouses/treehouses.github.io pull request #153
Opened 2019-09-12 18:23 UTC by vmnet8

Dear teammates,
I finished step 1-9,  added myself in team.md. 
Hope to join the team soon.

2019-09-12 19:02 UTC, dogi commented
@vmnet8 missing raw githack link ;)

2019-09-12 19:02 UTC, dogi requested changes
on hold until interview

2019-09-12 19:03 UTC, dogi commented
also congrats @vmnet8

2019-09-12 19:29 UTC, vmnet8 commented
again? haha.
https://raw.githack.com/vmnet8-OLE/vmnet8-OLE.github.io/team/#!pages/vi/team.md
please check.

2019-09-12 19:30 UTC, vmnet8 commented
> also congrats @vmnet8

thank you :)

2019-09-15 08:36 UTC, Liew211 approved these changes

2019-09-16 16:20 UTC, lmmrssa approved these changes

2019-09-16 16:24 UTC, dogi approved these changes

2019-09-16 16:24 UTC, dogi commented on pages/vi/team.md
> +|[vmnet8](profiles/vmnet8.md)|2019-09-11|
congrats @vmnet8 :)

2019-09-16 16:26 UTC, CalebProvost approved these changes

2019-09-16 16:35 UTC, merged