added myself (Xavier) to team of interns
treehouses/treehouses.github.io pull request #168
Opened 2019-09-20 02:00 UTC by xavierh93

https://raw.githack.com/Xavierh93/Xavierh93.github.io/team-update/#!pages/vi/team.md

2019-09-20 02:47 UTC, CalebProvost approved these changes
Good work.
Remember, we know who's creating the PR, so that part isn't needed in the title. 
Also, think of the title as more of what happens to the files/code - put more of what you performed into the commit messages.

2019-09-20 23:04 UTC, dogi requested changes
on hold until interview

2019-09-23 16:05 UTC, dogi approved these changes

2019-09-23 16:05 UTC, dogi commented on pages/vi/team.md
> +|[Xavierh93](profiles/Xavierh93.md)|2019-09-19|
congrats @xavierh93 ;)

2019-09-23 16:14 UTC, merged