Create contribution templates
treehouses/treehouses.github.io pull request #215
Opened 2019-10-11 22:55 UTC by Thais-ra

Add templates of pull request and creation of issues.

2019-10-11 23:27 UTC, CalebProvost commented
Thank you @Thais-ra!
I'll point the rest of our members in our group to review it.
Feel free to [look us over](https://treehouses.io/#!pages/vi/firststeps.md) and see if you'd like to join the rest of us Virtual Interns. We could always benefit from someone with your skills.
Just drop in on our [gitter chatroom]() and say hello.

Additionally, could you put this on a new branch for this pull request?

For the rest of the interns, the githack link is:
https://raw.githack.com/Thais-ra/treehouses.github.io/master/#!Templates/ISSUE_TEMPLATE.md
and
https://raw.githack.com/Thais-ra/treehouses.github.io/master/#!Templates/PULL_REQUEST_TEMPLATE.md

2019-10-21 19:26 UTC, pattanawadee88 requested changes
For PULL_REQUEST_TEMPLATE.md, please also include the raw.githack link. :)

2019-10-21 19:37 UTC, pattanawadee88 commented on Templates/PULL_REQUEST_TEMPLATE.md
> +## Solve (Issues)
I think this line should be (fixes #issue_number) and this should be at the end of pull request title

2019-10-30 23:05 UTC, dogi commented
https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/.github/ISSUE_TEMPLATE.md

2019-10-31 00:12 UTC, kjong commented
I've updated the templates. Requesting reviews.

2019-10-31 02:46 UTC, vmnet8 approved these changes
good

2019-10-31 10:12 UTC, dogi commented
@kjong can you also fix PR template?

2019-10-31 18:33 UTC, kjong commented
Are there any particular changes you are looking for?
I modeled it after the one at: https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2019-10-31 18:52 UTC, pattanawadee88 approved these changes

2019-10-31 19:16 UTC, CalebProvost requested changes
To make things just a little bit easier, have the raw.githack link example in the PR template:
`https://raw.githack.com/UserName/Repository/Branch/Path/To/File.md`

2019-10-31 23:41 UTC, CalebProvost approved these changes

2019-11-01 10:00 UTC, merged