access kolibri using docker new blog
treehouses/treehouses.github.io pull request #221
Opened 2019-10-14 23:11 UTC by irisb1701

https://raw.githack.com/treehouses/treehouses.github.io/kolibri/#!./pages/blog/20191014-kolibri.md

2019-10-16 16:59 UTC, CalebProvost requested changes

2019-10-16 16:59 UTC, CalebProvost commented on pages/blog/20191014-kolibri.md
> +1. Copy the link provided: `docker run -v /data/save/location:/root/.kolibri -p 8080:8080 treehouses/kolibri
> Copy the link provided: `docker run -v /data/save/location:/root/.kolibri -p 8080:8080 treehouses/kolibri

forgot the ending `

2019-10-16 16:59 UTC, CalebProvost commented on pages/blog/20191014-kolibri.md
> +1. Replace /data/save/location with /srv/kolibri
> Replace /data/save/location with /srv/kolibri

Should the directories be in code blocks?
"Replace `/data/save/location` with `/srv/kolibri`"

2019-10-17 23:33 UTC, CalebProvost approved these changes

2019-10-18 23:33 UTC, XavierElon approved these changes
Worked for me

2019-10-18 23:33 UTC, XavierElon commented on pages/blog/20191014-kolibri.md
> +1. Copy the link provided: `docker run -v /data/save/location:/root/.kolibri -p 8080:8080 treehouses/kolibri
You forgot a tick here to close the coding statement

2019-10-19 01:29 UTC, dogi approved these changes

2019-10-19 01:30 UTC, merged