Vim Tutorial Link
treehouses/treehouses.github.io pull request #233
Opened 2019-10-20 15:05 UTC by sonAndrew

Added a section for  **Vim Tutorial** and **Link** in **Step 0**.

2019-10-20 20:23 UTC, pattanawadee88 commented
please put the raw.githack link for us to review! :)

2019-10-21 18:03 UTC, pattanawadee88 requested changes
Personally, I like your idea but we do not want to make firststeps page too long. It would be better if you just introduce a few sentences of Vim and add the Vim link.

2019-10-21 22:19 UTC, CalebProvost commented
> Personally, I like your idea but we do not want to make firststeps page too long. It would be better if you just introduce a few sentences of Vim and add the Vim link.

Either that or link it to a page which has a simple tutorial, whether it be the one you made, or an external source.

2019-10-23 10:37 UTC, CalebProvost approved these changes

2019-10-23 17:37 UTC, pattanawadee88 approved these changes

2019-10-23 17:38 UTC, merged