modified team.md
treehouses/treehouses.github.io pull request #270
Opened 2019-11-12 17:51 UTC by Nida8930

N/A

### Description
I recently completed the first steps and added my user name to the team list

### Raw.Githack preview link
https://raw.githack.com/Nida8930/Nida8930.github.io/branch-internlist/#!pages/vi/team.md

2019-11-12 19:25 UTC, pattanawadee88 approved these changes

2019-11-14 01:34 UTC, dogi requested changes
on hold until interview

2019-11-14 01:36 UTC, dogi commented
by the way @Nida8930 is "nedavis2" also you?

2019-11-15 04:52 UTC, Nida8930 commented
@dogi Yes it is, I'm not sure how it came up in here, its an old account not associated with my current school.

2019-11-16 00:39 UTC, dogi approved these changes

2019-11-16 00:39 UTC, dogi commented on pages/vi/team.md
> +|[Nida8930](profiles/Nida8930.md)|2019-11-12|
@Nida8930 congrats

2019-11-16 00:48 UTC, merged