Create 20191202-blogfornewintern.md
treehouses/treehouses.github.io pull request #290
Opened 2019-12-02 20:14 UTC by pattanawadee88

https://raw.githack.com/treehouses/treehouses.github.io/add-blog/#!./pages/blog/20191202-blogfornewintern.md

2019-12-03 02:18 UTC, pattanawadee88 commented
> Great work !
> At what time are they been held the hangout meetings and is it central time pacific time

you will know the schedule of the meeting after you are done with the First Steps :)

2019-12-16 04:10 UTC, irisb1701 approved these changes

2019-12-16 19:02 UTC, kjong requested changes

2019-12-16 19:02 UTC, kjong commented on pages/blog/20191202-blogfornewintern.md
> +If you see this message `@/all Hello Team my name is .... I'd like to become a virtual intern. What is the next step?`, you need to welcome the new intern and send this link `https://treehouses.io/#!
Do we want to send them `https://treehouses.io/#!./pages/vi/firststeps.md` instead of `https://treehouses.io/#!./pages/vi/sshpi.md`?

2019-12-16 20:48 UTC, kjong approved these changes

2019-12-16 21:12 UTC, dogi approved these changes

2019-12-16 21:12 UTC, merged