Branch new sravya 07
treehouses/treehouses.github.io pull request #369
Opened 2020-01-10 10:29 UTC by sravya71

Please make sure to:
- Add "Sravya71" to the team.md file

### Description
Addded Sravya71 to team.md file.

### Raw.Githack preview link
https://raw.githack.com/sravya71/Sravya.treehouses.github.io/Branch-new-Sravya-07/pages/vi/team.md

2020-01-10 10:31 UTC, kjong approved these changes

2020-01-10 10:39 UTC, dogi requested changes
on hold until interview :)

@sravya71 congrats !!!

2020-01-10 10:39 UTC, dogi commented
thanks @kjong

2020-01-10 14:51 UTC, LordJashin32 approved these changes

2020-01-14 06:01 UTC, dogi approved these changes

2020-01-14 06:11 UTC, lmmrssa approved these changes
Looks good

2020-01-14 06:22 UTC, merged