create linhle199611.md
treehouses/treehouses.github.io pull request #371
Opened 2020-01-13 06:33 UTC by linhle199611

https://raw.githack.com/linhle199611/linhle199611.github.io/linhle/#!pages/vi/profiles/linhle199611.md

2020-01-13 08:09 UTC, kjong requested changes
Please try and use markdown instead of html (eg. `#` instead of `<h1>`).
One of the goals of this exercise is to become more familiar with markdown.

2020-01-13 19:30 UTC, dogi reviewed
good start :)

2020-01-13 19:30 UTC, dogi commented on pages/vi/profiles/linhle199611.md
> +> - My Facebook: [Linh](https://www.facebook.com/linhlinhlinhlinh.lelelele) <br>
@linhle199611 please also do not use `<br>`

2020-01-13 20:45 UTC, closed without merging

2020-01-15 20:41 UTC, dogi commented
@linhle199611 why would you not just change it to markdown?