ProfileNeethuMohan.md
treehouses/treehouses.github.io pull request #379
Opened 2020-01-20 12:39 UTC by Neethu-Mohan

### Raw.Githack preview link

[Preview](https://raw.githack.com/Neethu-Mohan/Neethu-Mohan.github.io/Profile/pages/vi/profiles/Neethu-Mohan.md)

2020-01-20 15:27 UTC, Nida8930 requested changes
You're on the right track! I liked that you used a table. 

In your raw.githack link you need to add `#!` after Profile/ and before pages, so it links to a preview and not raw markdown. 
Also on your page it does not appear that your .jpg is loading correctly.

2020-01-20 19:13 UTC, jamjakpa commented
https://raw.githack.com/Neethu-Mohan/Neethu-Mohan.github.io/Profile/<code>somethinghastogoinhere</code>/pages/vi/profiles/Neethu-Mohan.md

2020-01-21 10:33 UTC, Neethu-Mohan commented
Please check https://neethu-mohan.github.io/#!index.md and https://raw.githack.com/Neethu-Mohan/Neethu-Mohan.github.io/Profile/#!pages/vi/profiles/Neethu-Mohan.md

2020-01-21 10:57 UTC, jamjakpa approved these changes

2020-01-21 11:26 UTC, Nida8930 commented
> https://raw.githack.com/Neethu-Mohan/Neethu-Mohan.github.io/Profile/`somethinghastogoinhere`pages/vi/profiles/Neethu-Mohan.md

Just one `/` between Profile and pages.

2020-01-21 11:31 UTC, Nida8930 approved these changes
Looks good, good job.

2020-01-21 12:52 UTC, merged

2020-01-22 03:29 UTC, dogi commented on pages/vi/profiles/Neethu-Mohan.md
> +![](https://raw.githubusercontent.com/Neethu-Mohan/Neethu-Mohan.github.io/Profile/pages/vi/profiles/images/MyCity.jpg)
this should be a relative link