commented out "Other helpful links and videos"
treehouses/treehouses.github.io pull request #472
Opened 2020-03-27 00:11 UTC by jayala-29

Fixes #471 

### Description
Commented out "Other helpful links and videos" in Markdown file just in case the link is wanted later down the road when page requested is populated with content

### Raw.Githack preview link
https://raw.githack.com/jayala-29/jayala-29.github.io/patch-4/#!pages/vi/vagranttutorial.md

2020-03-27 22:24 UTC, LordJashin32 requested changes
The link doesn't need removal but needs to be updated to: https://treehouses.io/#!./pages/vi/faq.md#Helpful_Links
Which would be in the file: ~~vi~~ faq.md#Helpful_Links

2020-03-27 23:20 UTC, kjong approved these changes

2020-03-27 23:20 UTC, jayala-29 commented
Changed link to reach valid page

2020-03-28 00:50 UTC, dogi approved these changes

2020-03-28 00:56 UTC, LordJashin32 approved these changes
New githack. Works. Cheers. https://raw.githack.com/jayala-29/jayala-29.github.io/726a48f5a8b195dd452d8e215c8ac1392347ed4c/#!pages/vi/vagranttutorial.md

2020-03-28 01:06 UTC, merged