update firststeps.md (fixes #574)
treehouses/treehouses.github.io pull request #575
Opened 2020-05-04 07:45 UTC by ali18997

Fixes #574

### Description
removed period from the only bullet point in hardware requirements having it.

### Raw.Githack preview link
https://github.com/ali18997/ali18997.github.io/blob/master/pages/vi/firststeps.md

2020-05-04 08:04 UTC, law-lin requested changes
This PR was made from your `master` branch. Make sure you create a new branch and make the PR from that branch.

2020-05-04 19:22 UTC, dogi approved these changes

2020-05-04 19:25 UTC, dogi approved these changes

2020-05-04 19:26 UTC, merged

2020-05-19 03:01 UTC, ali18997 commented
> This PR was made from your `master` branch. Make sure you create a new branch and make the PR from that branch.

Got it, I have made new branches for all the PRs after this one.