Update pi-setup.md
treehouses/treehouses.github.io pull request #58
Opened 2019-08-21 06:45 UTC by ArranHL

Small Changes on the pi-setup.md

2019-08-21 22:33 UTC, Liew211 approved these changes

2019-08-21 22:52 UTC, Liew211 commented
![](https://www.balena.io/static/steps-8006dca57323756b1b84fb9408742409.gif)

2019-08-22 00:50 UTC, dogi requested changes
we should remove both old pictures

2019-08-22 00:52 UTC, Liew211 commented
@dogi  Done :)

2019-08-22 00:55 UTC, dogi approved these changes

2019-08-22 00:56 UTC, merged