Cyberbranch
treehouses/treehouses.github.io pull request #664
Opened 2020-07-09 06:45 UTC by CyberHuey

Fixes #issue_number

### Description
https://raw.githack.com/cyberhuey/CyberHuey.github.io/Cyberbranch/#!pages/vi/profiles/CyberHuey.md

### Raw.Githack preview link
raw.githack link to page(s) changed.

e.g. https://raw.githack.com/UserName/Repository/Branch/Path/To/File.md

2020-07-10 09:22 UTC, dogi commented
@CyberHuey nice start ... it would be nicer if title and description of PR would be more up to code ;)
please fix that

2020-07-10 12:59 UTC, CyberHuey commented
What exactly do you mean more up to code. I don't mind making adjustments

2020-07-11 02:43 UTC, jayala-29 commented
@CyberHuey   

you left the Pull Request description template as it was, you need to replace with what you did 

e.g.  update the description with what you did, take `https://raw.githack.com/cyberhuey/CyberHuey.github.io/Cyberbranch/#!pages/vi/profiles/CyberHuey.md` and put it under the `Raw.Githack preview link` section

2020-07-11 17:00 UTC, CyberHuey commented
@dogi @jayala-29 

Please check my latest updates in the descriptions as requested

2020-07-15 17:08 UTC, Pavivenkatesan commented on pages/vi/profiles/CyberHuey.md
> +- HMTL5/CSS
HTML 5... Spell check

2020-07-15 17:09 UTC, Pavivenkatesan commented on pages/vi/profiles/CyberHuey.md
> +- HMTL5/CSS
Great to know you Huey !

2020-07-15 17:09 UTC, Pavivenkatesan requested changes
See comments

2020-07-17 17:01 UTC, CyberHuey reviewed
Spelling corrected!

2020-07-18 00:13 UTC, law-lin approved these changes

2020-07-19 02:16 UTC, dogi approved these changes

2020-07-19 02:16 UTC, merged