Update vagranttutorial.md (fixes #698)
treehouses/treehouses.github.io pull request #738
Opened 2020-08-21 08:09 UTC by gautamsethi1

Fixes #698 

### Description
Adding troubleshooting instructions if prospective interns already have a VM running.

### Raw.Githack preview link
https://raw.githack.com/gautamsethi1/gautamsethi.github.io/adding-instructions/#!pages/vi/vagranttutorial.md

2020-08-21 17:29 UTC, anthonyhvo12 requested changes
This is a great addition. I think putting the note at the beginning is more helpful as other interns don't have to worry about the rest of the steps.

2020-08-21 23:24 UTC, gautamsethi1 commented
> This is a great addition. I think putting the note at the beginning is more helpful as other interns don't have to worry about the rest of the steps.

Would this be a better spot? 

![Screen Shot 2020-08-21 at 4 23 31 PM](https://user-images.githubusercontent.com/33525794/90942468-c8cd0600-e3ca-11ea-80bb-b913010836d4.png)

2020-08-24 15:49 UTC, anthonyhvo12 commented
![image](https://user-images.githubusercontent.com/43098273/91066492-00061600-e65c-11ea-8a90-d077169d07a7.png)
I think we can add the note right after "move on to the next steps" here.

2020-08-31 21:04 UTC, dogi commented on pages/vi/vagranttutorial.md
> +- Use the command `vagrant up [name of cli folder]`
this is kinda wrong

2020-08-31 21:05 UTC, closed without merging