Personal page
treehouses/treehouses.github.io pull request #748
Opened 2020-10-27 21:45 UTC by thatgirlprogrammer

Fixes #issue_number

### Description
Description of changes made.

### Raw.Githack preview link
raw.githack link to page(s) changed.

e.g. https://raw.githack.com/UserName/Repository/Branch/Path/To/File.md

2020-10-27 21:48 UTC, thatgirlprogrammer commented
Created thatgirlprogrammer.md
https://raw.githack.com/thatgirlprogrammer/thatgirlprogrammer.github.io/personal_page/#!pages/vi/profiles/thatgirlprogrammer.md

2020-10-31 09:19 UTC, dogi requested changes

2020-10-31 09:19 UTC, dogi commented on pages/vi/profiles/thatgirlprogrammer.md
> +```print('Hello there')```
single not triple ticks

2020-10-31 09:19 UTC, dogi commented on pages/vi/profiles/thatgirlprogrammer.md
> +Linkedin: [linkedin] (https://www.linkedin.com/in/amy-mullins-0a5858111/)
no spaces between the brackets

2020-10-31 09:20 UTC, dogi commented
@thatgirlprogrammer very awesome profile page ...
... please fix these little errors

2020-11-02 17:59 UTC, dogi approved these changes

2020-11-02 18:00 UTC, merged