update firststeps.md (issue #845)
treehouses/treehouses.github.io pull request #847
Opened 2022-02-17 15:21 UTC by RCW2000

Fixes #845

### Description
changed the Gitter Chat link, in The Steps section, so that it now goes to the chat page

### Raw.Githack preview link
raw.githack link to page(s) changed.

(https://raw.githack.com/RCW2000/RCW2000.github.io/chatlink/#!pages/vi/firststeps.md)

2022-02-19 03:30 UTC, dogi requested changes

2022-02-19 03:30 UTC, dogi commented on pages/vi/firststeps.md
> +**We also want you to keep us updated on a relatively good amount in the [Gitter chat](https://treehouses.io/#!pages/chat.md) as you complete these steps. We will ask you to send us messages, links,
please make this link a relative one instead of absolute

2022-02-19 04:10 UTC, RCW2000 commented on pages/vi/firststeps.md
> +**We also want you to keep us updated on a relatively good amount in the [Gitter chat](https://treehouses.io/#!pages/chat.md) as you complete these steps. We will ask you to send us messages, links,
it should be fixed now

2022-02-21 09:46 UTC, dogi approved these changes

2022-02-21 09:46 UTC, merged